### PR TITLE
[SIM_FLUTTER-34] [Integrate] Implement user can deposit cash

### PR DESCRIPTION
**Pull request by jescabillas**
### Issue
[Backlog](https://framgiaph.backlog.com/view/SIM_FLUTTER-34)
[Slack](https://sun-philippine.slack.com/archives/C059L7XAXFB/p1689054742325319)

### Definition of done
- [x] User will be able to deposit through dashboard page
- [x] User will be able to deposit through account details page
- [x]  Display necessary messages for validation errors
- [x] Once the transaction is successful, remove the deposit form and display modal/pop-up for success message
- [x] Account balance will be updated accordingly in dashboard and account details page

### Notes
Only in deposit modal/pop-up form

### Recording

https://github.com/framgia/sph-flutter/assets/114911074/1437c261-2aa2-4bc6-9515-b72c12983eb2

### CODE REVIEW

**Review by jstephend-sun — DISMISSED** [review]
Approved #58

review time: 2mins
comments: 0

**Comment by Dbulawan13** [comment]
Comment:

- [ ] Should be able to enter and deposit amount with 2 decimal places. Please also include changes in withdraw functionality since it can't also enter or withdraw an amount with 2 decimal places.
`Note: Should only be able to input an amount with 2 decimal places.`



Comment: 1

**Comment by Dbulawan13** [comment]
Comment:

- [ ] When the user triggers the empty validation, the confirm button should remain disabled, just like the withdraw modal.

https://github.com/framgia/sph-flutter/assets/86758474/1b9b5129-52c5-46ea-a307-2111b631c66f

Comment: 1

**Review by Dbulawan13 — DISMISSED** [review]
Approve PR #58 

Working:
- Able to deposit cash
- Able to enter numbers with two decimal places in both deposit and withdraw modal
- Validations are rendered correctly

https://github.com/framgia/sph-flutter/assets/86758474/6cd92b73-39d7-427d-86ca-c0e77daff829

Testing Hours: 2
Comments: 2
Iterations: 2

**Review by Dbulawan13 — APPROVED** [review]

**Pull request merged**
