### PR TITLE
[SIM_FLUTTER-94] [Integrate] User should stay logged in once user goes back to the application

### PR DESCRIPTION
**Pull request by jstephend-sun**
### Issue links
- [backlog](https://framgiaph.backlog.com/view/SIM_FLUTTER-94)
- [slack](https://sun-philippine.slack.com/archives/C059L7XAXFB/p1687760355064169)
- dependent #27 

### Definition of Done
- [x] if there is previous login token
  - check if it is valid
  - redirect to homescreen if valid

### Notes
- app goes back to login page, but the form is not shown if there is previous login token
 
### Recording
- 1

[screen-capture (1).webm](https://github.com/framgia/sph-flutter/assets/95029803/fe6848c1-4684-4492-9480-825e01028581)

### CODE REVIEW

**Comment by Dbulawan13** [comment]
Comment:

- [ ] Having hard time logging in either in actual device and in the web view. 



image

Comment: 1

**Comment by Dbulawan13** [comment]
Comment:

- [ ] Unable to logout properly using an actual device

https://github.com/framgia/sph-flutter/assets/86758474/32385e93-5dcb-4134-b621-7c7981c09932

Web View is working properly:

https://github.com/framgia/sph-flutter/assets/86758474/92efedec-c8f0-4cbc-ac5c-4c2f8f42cba8

Comment: 1

**Review by Dbulawan13 — DISMISSED** [review]
Approve PR #30 

Working:
- If user is already logged in. Able to stay logged in once user reload or goes back to the application
- Able to login
- Able to logout
- Comments have been fixed

https://github.com/framgia/sph-flutter/assets/86758474/4ac2fd15-d8b6-4a8d-86fd-5d0043cf9b20

https://github.com/framgia/sph-flutter/assets/86758474/5e0ce6b8-ec23-4214-b5e0-e66f433ee0b9

Testing Hours: 2h
Comments: 2
Iterations: 2

**Review by RDLegs — APPROVED** [review]
The code seems fine with me

**Pull request merged**
