### PR TITLE
[SIM_FLUTTER-13] [INTEGRATE] Display searched user

### PR DESCRIPTION
**Pull request by egiegarciano14**
### Issue links
- [Backlog](https://framgiaph.backlog.com/view/SIM_FLUTTER-13)
- [Slack](https://sun-philippine.slack.com/archives/C059L7XAXFB/p1688115005680839)

### Definition of Done
- [x] Display list of searched users

### Note
- Dependent to [pr#27](https://github.com/framgia/sph-flutter/pull/27)

### Recording
image

### CODE REVIEW

**Comment by Dbulawan13** [comment]
Comment:

- [x] No result will display if user frequently search a user that does not exist


https://github.com/framgia/sph-flutter/assets/86758474/1f759319-4b4e-4819-abf7-09e7eddc8411

https://github.com/framgia/sph-flutter/assets/86758474/02ad6921-3ef2-43e6-a657-b67d14d74da2

Comment: 1

**Comment by Dbulawan13** [comment]
Comment:

- [ ] An error will display when admin login.




Comment: 1

**Review by Dbulawan13 — DISMISSED** [review]
Approved #39 

Working:
- Able to search for user and admin account via lastname, middlename and firstname
- No result will display if account does not exist

https://github.com/framgia/sph-flutter/assets/86758474/adcd28d7-7ee4-413f-821c-55616f1234bc

Testing Hours: 2
Comments: 2
Iterations: 2

**Review by jstephend-sun — DISMISSED** [review]
Approved #39

review time: 10mins
comments: 0
iteration: 1st review

**Review by jstephend-sun — APPROVED** [review]

**Pull request merged**
